import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LoadingProvider } from "@/context/LoadingContext";
import { AuthProvider } from "@/context/AuthContext";
import { QueryProvider } from "@/providers/QueryProvider";
import Providers from "@/providers/StoreProvider";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-poppins font-semibold`}>
        <QueryProvider>
          <AuthProvider>
            <Providers>
              <LoadingProvider>{children}</LoadingProvider>
              <Toaster />
            </Providers>
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
